---
all:
  children:
    web_servers:
      hosts:
        web-prod-01:
          ansible_host: 192.168.1.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

        web-prod-02:
          ansible_host: 192.168.1.11
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    db_servers:
      hosts:
        db-prod-01:
          ansible_host: 192.168.1.20
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

  vars:
    ansible_python_interpreter: /usr/bin/python3
